# Generated by Django 3.2.8 on 2024-04-23 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_auto_20240423_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_codes', to='referral.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='activated_referral_codes',
            field=models.ManyToManyField(related_name='activated_by_users', to='referral.ReferralCode'),
        ),
    ]
