# Generated by Django 3.2.8 on 2024-04-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0007_auto_20240424_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=15),
        ),
    ]
